
export const FFETCH_CAMPERVANS = 'FFETCH_CAMPERVANS';
export const FFETCH_CAMPERVANS_SUCCESS = 'FFETCH_CAMPERVANS_SUCCESS';

export const GET_RENTAL = 'GET_RENTAL';
export const GET_RENTAL_SUCCESS = 'GET_RENTAL_SUCCESS';
export const CLEANUP_SELECTED = 'CLEANUP_SELECTED';


